[package]
name = "mdsecheck"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = { version = "0.5.0", default-features = false, features = ["asm"] }
ark-poly = "0.5.0"
indexmap = "2.7.1"
rand = "0.8.5"

[dev-dependencies]
ark-bn254 = "0.5.0"
rand_chacha = "0.3.0"
